application:
    appName: sgc

spring:
    application:
        name: srsservice
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/sgc
        username: sgc
        password: sgc
        hikari:
            poolName: Hikari
            auto-commit: false
    jackson:
        deserialization:
            fail-on-unknown-properties: false
    liquibase:
        change-log: classpath:/db/master.xml            
    jpa:
        database: POSTGRESQL
        show-sql: true
        open-in-view: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false

server:
    port: 8080